# Generated by Django 4.0.4 on 2022-05-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='country',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='county',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='town',
        ),
    ]
